---
title: "lab4_visu"
output: html_document
date: "2026-09-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Visualisation dudalling

```{r load}
library(igraph)
g <- make_graph("Zachary")
plot(g)
```

## EDA
### Node charactersists

```{r EDA node charactersists}
gmat <- as_adjacency_matrix(g, type = "both", sparse = FALSE)

# directed?
isSymmetric.matrix(gmat)

# Size
# number of nodes
vcount(g)
# number of edges
ecount(g)

par(mfrow = c(2, 2))

# plot 1: degree distribution
hist(table(igraph::degree(g)), xlab='in-degree', main= 'Histogram of in-degree')


# plot 2: alle mogelijke trihoekjes
trans = igraph::transitivity(g, type = c("localundirected"), isolates = c("NaN", "zero"))
hist(trans, xlab='Transitivity', main= 'Histogram of transitivity')

# plot 3: betweenness
between = igraph::betweenness(g, directed = FALSE, normalized = T)
hist(trans, xlab='Betweenness', main= 'Histogram of Normalised betweenness')

# plot 4: network
V(g)$size <- igraph::betweenness(g, directed = FALSE, normalized = T) * 100 + 10
V(g)$color <- igraph::betweenness(g, directed = FALSE, normalized = T) * 100
layout = layout_with_mds(g, dim=2)

plot(g, layout=layout)
title("Network visualisation")
```
# Edge characteristics

```{r edges}
igraph::dyad_census(g)

igraph::triad_census(g)

# I will use sna because it shows the names of the triads as well.
sna::triad.census(gmat)
unloadNamespace("sna")  

igraph::transitivity(g, type = "global")
sna::gtrans(gmat)

triad_g <- data.frame(sna::triad.census(gmat))


transitivity_g <- (3 * triad_g$X300)/(triad_g$X201 + 3 * triad_g$X300)
transitivity_g



```

```{r layout}
set.seed(2345)
l <- layout_with_dh(g)  #https://igraph.org/r/doc/layout_with_mds.html
plot(g, layout = l)

l  #let us take a look at the coordinates
l[1, 1] <- 4
l[34, 1] <- -3.5
plot(g, layout = l)


```

